import { NgModule } from "@angular/core";
import {
  MatAutocompleteModule,
  MatButtonModule,
  MatCardModule,
  MatCheckboxModule,
  MatDialogModule,
  MatDividerModule,
  MatFormFieldModule,
  MatIconModule,
  MatInputModule,
  MatListModule,
  MatPaginatorModule,
  MatProgressBarModule,
  MatProgressSpinnerModule,
  MatRippleModule,
  MatSelectModule,
  MatSidenavModule,
  MatSlideToggleModule,
  MatSortModule,
  MatTableModule,
  MatTabsModule,
  MatToolbarModule,
  MatTooltipModule,
  MatBadgeModule
} from "@angular/material";
import { TextMaskModule } from "angular2-text-mask";

@NgModule({
  imports: [
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatIconModule,
    MatSidenavModule,
    MatListModule,
    MatToolbarModule,
    MatRippleModule,
    MatDialogModule,
    MatTabsModule,
    MatSelectModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatCheckboxModule,
    MatDividerModule,
    MatSlideToggleModule,
    MatTableModule,
    MatPaginatorModule,
    MatTooltipModule,
    TextMaskModule,
    MatSortModule,
    MatAutocompleteModule,
    MatBadgeModule
  ],
  exports: [
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatIconModule,
    MatSidenavModule,
    MatListModule,
    MatToolbarModule,
    MatRippleModule,
    MatDialogModule,
    MatTabsModule,
    MatSelectModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatCheckboxModule,
    MatDividerModule,
    MatSlideToggleModule,
    MatTableModule,
    MatPaginatorModule,
    MatTooltipModule,
    TextMaskModule,
    MatSortModule,
    MatAutocompleteModule,
    MatBadgeModule
  ],
  declarations: [],
  providers: []
})
export class MaterialModule {}
