import { NgModule } from "@angular/core";
import {
  MatCardModule,
  MatFormFieldModule,
  MatInputModule,
  MatButtonModule,
  MatIconModule,
  MatSidenavModule,
  MatListModule,
  MatToolbarModule,
  MatRippleModule,
  MatDialogModule,
  MatTabsModule,
  MatSelectModule,
  MatProgressBarModule,
  MatProgressSpinnerModule,
  MatCheckboxModule,
  MatDividerModule,
  MatSlideToggleModule,
  MatTableModule,
  MatPaginatorModule,
  MatTooltipModule,
  MatSortModule,
  MatDatepickerModule,
  MatAutocompleteModule
} from "@angular/material";
import { TextMaskModule } from "angular2-text-mask";

@NgModule({
  imports: [
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatIconModule,
    MatSidenavModule,
    MatListModule,
    MatToolbarModule,
    MatRippleModule,
    MatDialogModule,
    MatTabsModule,
    MatSelectModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatCheckboxModule,
    MatDividerModule,
    MatSlideToggleModule,
    MatTableModule,
    MatPaginatorModule,
    MatTooltipModule,
    TextMaskModule,
    MatSortModule,
    MatAutocompleteModule
  ],
  exports: [
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatIconModule,
    MatSidenavModule,
    MatListModule,
    MatToolbarModule,
    MatRippleModule,
    MatDialogModule,
    MatTabsModule,
    MatSelectModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatCheckboxModule,
    MatDividerModule,
    MatSlideToggleModule,
    MatTableModule,
    MatPaginatorModule,
    MatTooltipModule,
    TextMaskModule,
    MatSortModule,
    MatAutocompleteModule
  ],
  declarations: [],
  providers: []
})
export class MaterialModule {}
